"""Terminal / JSON / HTML report rendering for gate results."""

from __future__ import annotations

import html as _html
import json

SYMBOLS = {"pass": "✓", "fail": "✗", "warn": "!", "skip": "–"}


def counts(results):
    out = {"pass": 0, "fail": 0, "warn": 0, "skip": 0}
    for r in results:
        out[r.status] = out.get(r.status, 0) + 1
    return out


def summary_line(results):
    c = counts(results)
    total = len(results)
    line = f"{c['pass']}/{total} passed"
    extras = []
    if c["fail"]:
        extras.append(f"{c['fail']} failed")
    if c["warn"]:
        extras.append(f"{c['warn']} warning")
    if c["skip"]:
        extras.append(f"{c['skip']} skipped")
    if extras:
        line += " (" + ", ".join(extras) + ")"
    return line


def render_text(results, artifact_name):
    lines = [f"model-gate  artifact: {artifact_name}", ""]
    for r in results:
        sym = SYMBOLS.get(r.status, "?")
        lines.append(f"  {sym} {r.name:<10} {r.status:<4}  {r.detail}")
    lines += ["", summary_line(results)]
    return "\n".join(lines)


def render_dict(results, artifact_name):
    return {
        "artifact": artifact_name,
        "summary": {"total": len(results), **counts(results)},
        "gates": [r.to_dict() for r in results],
    }


def render_json(results, artifact_name):
    return json.dumps(render_dict(results, artifact_name), indent=2)


def render_html(results, artifact_name):
    """Standalone HTML report — no external assets."""
    rows = []
    for r in results:
        cls = r.status
        rows.append(
            "<tr class='%s'><td>%s</td><td>%s</td>"
            "<td>%s</td><td>%.1f</td></tr>"
            % (
                cls,
                SYMBOLS.get(r.status, "?"),
                _html.escape(r.name),
                _html.escape(r.detail),
                r.duration_ms,
            )
        )
    overall = "PASS" if all(r.status != "fail" for r in results) else "FAIL"
    banner = "ok" if overall == "PASS" else "bad"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>model-gate report — {_html.escape(artifact_name)}</title>
<style>
body {{ font-family: -apple-system, "Segoe UI", Helvetica, Arial, sans-serif;
       max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; }}
.banner {{ padding: 1rem 1.5rem; border-radius: 8px; margin-bottom: 1.5rem; }}
.banner.ok {{ background: #e6f6ec; border: 1px solid #34a853; }}
.banner.bad {{ background: #fdecea; border: 1px solid #d93025; }}
.banner h1 {{ margin: 0 0 .25rem; font-size: 1.4rem; }}
table {{ width: 100%; border-collapse: collapse; }}
th, td {{ text-align: left; padding: .5rem .75rem; border-bottom: 1px solid #e0e0e0; vertical-align: top; }}
tr.pass td:first-child {{ color: #1e8e3e; font-weight: bold; }}
tr.fail td:first-child {{ color: #d93025; font-weight: bold; }}
tr.warn td:first-child {{ color: #b06000; font-weight: bold; }}
tr.skip td:first-child {{ color: #80868b; font-weight: bold; }}
.mono {{ font-family: ui-monospace, Menlo, Consolas, monospace; }}
footer {{ margin-top: 1.5rem; color: #80868b; font-size: .85rem; }}
</style>
</head>
<body>
<div class="banner {banner}">
<h1>model-gate: {overall}</h1>
<div class="mono">{_html.escape(summary_line(results))} — {_html.escape(artifact_name)}</div>
</div>
<table>
<thead><tr><th></th><th>Gate</th><th>Detail</th><th>ms</th></tr></thead>
<tbody>
{''.join(rows)}
</tbody>
</table>
<footer>Generated by model-gate (zero dependencies). Gate statuses: pass / fail / warn / skip.</footer>
</body>
</html>
"""
